name: buildJar
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    
    - name: Upload Lavalink.jar
      uses: actions/upload-artifact@v2
      with:
           name: Lavalink Artifact
           path: ./LavalinkServer/build/libs/Lavalink.jar
           
    - name: Checkout
      uses: actions/checkout@v2
